exclude: '.pre-commit-config.yaml|.vscode/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-vcs-permalinks
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
          - --top-keys=_id
      - id: sort-simple-yaml
        files: '.yaml$'
      - id: check-symlinks
      - id: check-yaml
        exclude: '(.*-ci|ci/.+)\.yml$'
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-tabs
        exclude: '(\.tsv|Makefile)$'

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.6
    hooks:
      - id: pydoclint 
        args: [--style=sphinx]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # - repo: https://github.com/thclark/pre-commit-sphinx
  #   rev: 0.0.1
  #   hooks:
  #     - id: build-docs
  #       args: ['--cache-dir', 'docs/_build/doctrees', '--html-dir', 'docs/_build/html', '--source-dir', 'docs/source']
  #       language_version: python3
