name: test

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: 3.12
      - name: Set up environment variables
        run: echo "Environment variables set up"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
      - name: Install dependencies
        run: |
            pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest tests/
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
    
        
        