name: tests

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
            python-version: 3.12
      - name: Set up environment variables
        working-directory: ./nmdc_ms_metadata_gen
        run: echo "Environment variables set up"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BIO_API_KEY: ${{ secrets.BIO_API_KEY }}
      - name: Install dependencies
        run: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install -e .
      - name: Run tests
        working-directory: ./nmdc_ms_metadata_gen
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BIO_API_KEY: ${{ secrets.BIO_API_KEY }}
        run: pytest -x -r tests/
