name: tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: 3.12
      - name: Set up environment variables
        working-directory: ./nmdc_ms_metadata_gen
        run: echo "Environment variables set up"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BIO_API_KEY: ${{ secrets.BIO_API_KEY }}
      - name: Install dependencies
        run: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - name: Run tests
        working-directory: ./nmdc_ms_metadata_gen
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BIO_API_KEY: ${{ secrets.BIO_API_KEY }}
        run: pytest -r tests/
